apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'GCP Storage Action'
description: 'Uploads and downloads files to/from Google Cloud Storage.'

inputs:
  source_file:
    description: 'The file path to be sourced from. Can be a local file or a GCP storage file (gs://).'
    required: true
  destination_file:
    description: 'The file path to be uploaded to. Can be a local file or a GCP storage file.'
    required: true
  application_credentials:
    description: 'Base64-encoded IAM credentials for accessing the GCP bucket.'
    required: true
  project_id:
    description: 'The project ID that the bucket lives under.'
    required: true
  flags:
    description: 'Additional flags to be passed to the gsutil command.'
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Decode GCP Credentials
      uses: docker://google/cloud-sdk
      shell: bash
      run: |
        echo "${{ inputs.application_credentials }}" | base64 --decode > gcp-credentials.json
        echo "Decoded GCP credentials"

    - name: Set GCP Project ID
      uses: docker://google/cloud-sdk
      shell: bash
      run: |
        gcloud auth activate-service-account --key-file=gcp-credentials.json
        gcloud config set project ${{ inputs.project_id }}

    - name: Transfer Files
      uses: docker://google/cloud-sdk
      shell: bash
      run: |
        gsutil ${{ inputs.flags }} cp ${{ inputs.source_file }} ${{ inputs.destination_file }}
      env:
        GOOGLE_APPLICATION_CREDENTIALS: gcp-credentials.json

